name: Tests
on:
  push:
jobs:
  Tests-Linux-MacOS:
    strategy:
      matrix:
        # os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-12, macos-11, macos-10.15]
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Deno
        run: |
          brew install deno

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          set -x
          which deno
          sudo $(which deno) test --allow-all


  # Tests-Windows:
  #   strategy:
  #     matrix:
  #       os: [windows-2022, windows-2019]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Install Deno
  #       run: |
  #         choco install deno

  #     - name: Check out code
  #       uses: actions/checkout@v3

  #     - name: Run tests
  #       run: |
  #         deno test --allow-all
