name: Tests
on:
  push:
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -y install --no-install-recommends jq curl shellcheck file
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run tests bash version
        run: |
          ./tests/test-package-installations.sh
          ./tests/test-bin-get-installation.sh

      - name: Run tests Deno version
        run: |
          sudo deno test --allow-all
