name: Tests
on:
  push:
jobs:
  Tests:
    strategy:
      matrix:
        os:
          [
            ubuntu-18.04,
            ubuntu-20.04,
            ubuntu-22.04,
            macos-12,
            macos-11,
            macos-10.15,
            windows-2022,
            windows-2019,
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Deno
        shell: bash
        run: |
          if [[ "$OS" == 'Windows_NT' ]]; then
            choco install deno
          else
            curl -fsSL https://deno.land/install.sh | sudo DENO_INSTALL=/usr/local sh
          fi
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run tests
        shell: bash
        run: |
          export PATH="$HOME/.bin:$PATH"

          set -x 
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          env

          if [[ "$OS" == 'Windows_NT' ]]; then
            deno test --allow-all
          else
            sudo -E deno test --allow-all
          fi
